### ISSUE TITLE
Failed to install core package via symlink

### ISSUE THREAD

**Issue by forki** [Krzysztof-Cieslak/FSharp.Atom#10]
Steps to reproduce below:

1. Clone repo
2. build
3. try to install core package via symlink as describe in https://github.com/Krzysztof-Cieslak/FSharp.Atom/issues/3#issuecomment-98683388

**Atom Version**: 0.196.0
**System**: GOODEWIND
**Thrown From**: [core](https://github.com/Krzysztof-Cieslak/FSharp.Atom) package, v0.0.1

### Stack Trace

Failed to activate the core package

```
At path must be a string

TypeError: path must be a string
  at TypeError (native)
  at Object.fs.readdir (fs.js:800:11)
  at Object.fs.readdir (ATOM_SHELL_ASAR.js:422:24)
  at Core__projInit$ (D:\code\FSharp.Atom\src\core\lib\core.js:485:16)
  at Core__initialize$ (D:\code\FSharp.Atom\src\core\lib\core.js:447:5)
  at Core__activate$ (D:\code\FSharp.Atom\src\core\lib\core.js:433:5)
  at D:\code\FSharp.Atom\src\core\lib\core.js:1632:14
  at Object.module.exports.AtomFSharpCore.activate (D:\code\FSharp.Atom\src\core\lib\core.js:1652:26)
  at Package.module.exports.Package.activateNow (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:222:19)
  at C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:203:30
  at Package.module.exports.Package.measure (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15)
  at Package.module.exports.Package.activate (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package-manager.js:434:21)
  at C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package-manager.js:418:29
  at Config.module.exports.Config.transact (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package-manager.js:413:19)
  at PackageManager.module.exports.PackageManager.activate (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package-manager.js:394:46)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\atom.js:623:21)
  at Object.<anonymous> (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/Steffen/AppData/Local/atom/app-0.196.0/resources/app.asar/static/index.js:86:23)
  at window.onload (file:///C:/Users/Steffen/AppData/Local/atom/app-0.196.0/resources/app.asar/static/index.js:38:7)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
core, v0.0.1
paket, v0.0.1

# Dev
No dev packages
```

**Comment by forki** [comment]
I forgot to install the packages from the readme.

**Comment by forki** [comment]
still happens after installing the other packages.

**Atom Version**: 0.196.0
**System**: GOODEWIND
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.12.1

### Stack Trace

Failed to activate the core package

```
At path must be a string

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.readdir (fs.js:800:11)
    at Object.fs.readdir (ATOM_SHELL_ASAR.js:422:24)
    at Core__projInit$ (D:\code\FSharp.Atom\src\core\lib\core.js:485:16)
    at Core__initialize$ (D:\code\FSharp.Atom\src\core\lib\core.js:447:5)
    at Core__activate$ (D:\code\FSharp.Atom\src\core\lib\core.js:433:5)
    at D:\code\FSharp.Atom\src\core\lib\core.js:1632:14
    at Object.module.exports.AtomFSharpCore.activate (D:\code\FSharp.Atom\src\core\lib\core.js:1652:26)
    at Package.module.exports.Package.activateNow (C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:222:19)
    at C:\Users\Steffen\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:203:30
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.1
core, v0.0.1
paket, v0.0.1

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
During "installation discussion" with @isaacabraham we got same error on Windows 8.1 machine while trying opening standalone `fsx` file. Looks like issue is not connected with symlink and is reproduced also for normal copy of package in Atom package folder.  Will investigate it more Soon™
